<a href="https://colab.research.google.com/github/Prinzenrolle10/Credit-Card-Fraud-Detection/blob/main/Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Fraud-Detection mit Machine Learning und Deep Learning**

**Projektziel und Problemstellung**

---

In diesem Notebook wird ein Machine Learning Modell zur Erkennung von Kreditkartenbetrug entwickelt. Die grösste Herausforderung dieses Datensatzes ist die extreme Klassen-Unbalance. Betrugsfälle machen nur ca. 0.17% der Daten aus.
Es werden zwei Ansätze verglichen: ein klassisches, baumbasiertes Modell (XGBoost) und ein Deep Learning Ansatz zur Anomalieerkennung (Autoencoder).

In [ ]:
import pandas as pd
import numpy as np
import kagglehub
from sklearn.preprocessing import StandardScaler

In [ ]:
# Daten laden
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")
df = pd.read_csv(f"{path}/creditcard.csv")

print(f"Shape: {df.shape}")
df.head()

Using Colab cache for faster access to the 'creditcardfraud' dataset.
Shape: (284807, 31)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [ ]:
# Feature Engineering
df['event_timestamp'] = pd.to_datetime(df['Time'], unit='s', utc=True)
df = df.sort_values('event_timestamp').reset_index(drop=True)

df['time_diff'] = df['Time'].diff().fillna(0)
df['hour'] = (df['Time'] // 3600) % 24
df['amount_log'] = np.log1p(df['Amount'])

# Spalten umbenennen
v_cols = {f'V{i}': f'v{i}' for i in range(1, 29)}
df = df.rename(columns=v_cols)
df = df.rename(columns={'Amount': 'amount', 'Class': 'class'})

# Rollierende Features (1 Stunde Fenster)
df = df.set_index('event_timestamp', drop=False)
df['trans_count_1h'] = df['amount'].rolling('3600s').count().fillna(0.0)
df['amount_trans_count_1h'] = df['amount'].rolling('3600s').sum().fillna(0.0)
df = df.reset_index(drop=True)

# Feature-Liste definieren
feature_cols = [
    'time_diff', 'hour', 'trans_count_1h', 'amount_log', 'amount', 'amount_trans_count_1h'
] + [f'v{i}' for i in range(1, 29)]

print(f"Shape: {df.shape}")
df.head()

Shape: (284807, 37)

,Time,v1,v2,v3,v4,v5,v6,v7,v8,v9,...,v27,v28,amount,class,event_timestamp,time_diff,hour,amount_log,trans_count_1h,amount_trans_count_1h
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.133558,-0.021053,149.62,0,1970-01-01 00:00:00+00:00,0.0,0.0,5.014760,1.0,149.62
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.008983,0.014724,2.69,0,1970-01-01 00:00:00+00:00,0.0,0.0,1.305626,2.0,152.31
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,-0.055353,-0.059752,378.66,0,1970-01-01 00:00:01+00:00,1.0,0.0,5.939276,3.0,530.97
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,0.062723,0.061458,123.50,0,1970-01-01 00:00:01+00:00,0.0,0.0,4.824306,4.0,654.47
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.219422,0.215153,69.99,0,1970-01-01 00:00:02+00:00,1.0,0.0,4.262539,5.0,724.46

In [ ]:
# Train-Test-Split (chronologisch - 60-20-20)
n = len(df)
train_end = int(n * 0.6)
val_end = int(n * 0.8)

train_df = df.iloc[:train_end].copy()
val_df = df.iloc[train_end:val_end].copy()
test_df = df.iloc[val_end:].copy()

In [ ]:
# Skalierung
scaler = StandardScaler()

X_train = scaler.fit_transform(train_df[feature_cols])
y_train = train_df['class'].values

X_val = scaler.transform(val_df[feature_cols])
y_val = val_df['class'].values

X_test = scaler.transform(test_df[feature_cols])
y_test = test_df['class'].values

print(f"Train Shape: {X_train.shape}, Fraud Fälle: {sum(y_train)}")
print(f"Val Shape:   {X_val.shape}, Fraud Fälle: {sum(y_val)}")
print(f"Test Shape:  {X_test.shape}, Fraud Fälle: {sum(y_test)}")

Train Shape: (170884, 34), Fraud Fälle: 360
Val Shape:   (56961, 34), Fraud Fälle: 57
Test Shape:  (56962, 34), Fraud Fälle: 75

**ML-Pfad mit XGBoost und Optuna**

In [ ]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.48)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 17.0 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [ ]:
import logging
import sys
import numpy as np
import xgboost as xgb
import optuna
from sklearn.metrics import average_precision_score
from typing import Tuple, Dict, Any

In [ ]:
# Logging Setup
logging.basicConfig(
    level = logging.INFO,
    format = "%(asctime)s - %(levelname)s - %(message)s",
    force = True,
    stream = sys.stdout
)

logger = logging.getLogger(__name__)

Warum AUCPR statt ROC-AUC?

---

Da die Daten hochgradig unbalanciert sind, würde die klassische ROC-AUC-Metrik durch die Vielzahl der normalen Transaktionen ein trügerisch gutes Ergebnis liefern. Optuna wird daher auf den AUCPR (Area Under the Precision-Recall Curve) optimiert, da diese Metrik stark auf die Minderheisklasse (Betrufsfälle) fokussiert ist.

In [ ]:
# Optuna Objective Function
def objective(
    trial: optuna.Trial,
    X_tain: np.ndarray,
    y_train: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray,
) -> float:

  """
  Optuna Objective Funktion für das Tuning von XGBoost.
  Sucht nach den besten Hyperparametern für imbalanced Fraud-Daten.
  """

  # dynamische Berechnung der Balance für 'scale_pos_weight' als Anhaltspunkt
  # ratio = Anzahl normale Transaktionen / Anzahl Fraud
  ratio = float(np.sum(y_train == 0)) / float(np.sum(y_train == 1))

  # Suchraum für die Hyperparameter
  params = {
      "objective": "binary:logistic",
      "eval_metric": "aucpr",
      "tree_method": "hist",
      "device": "cuda",                # GPU in Colab
      "random_state": 42,
      "max_depth": trial.suggest_int("max_depth", 3, 10),
      "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.03, log=True),
      "n_estimators": trial.suggest_int("n_estimators", 100, 500),
      "subsample": trial.suggest_float("subsample", 0.5, 1.0),
      "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
      "scale_pos_weight": trial.suggest_float("scale_pos_weight", 1.0, ratio * 1.5),
  }

  # Modell intialisieren und trainieren
  model = xgb.XGBClassifier(**params)

  model.fit(
      X_train,
      y_train,
      eval_set=[(X_val, y_val)],
      verbose = False
  )

  # Vorhersagen auf dem Validierungsset
  pred_proba = model.predict_proba(X_val)[:, 1]

  # AUCPR-Metrik
  aucpr = average_precision_score(y_val, pred_proba)

  return aucpr

In [ ]:
# Main Tuning Function
def tune_and_train_xgboost(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray,
    n_trials: int = 20
) -> Tuple[xgb.XGBClassifier, Dict[str, Any]]:
    """
    Führt das Hyperparameter-Tuning durch und gibt das beste Modell zurück.
    """
    logger.info(f"Starte Tuning mit {n_trials} Trials...")

    # Optuna Study erstellen
    study = optuna.create_study(direction="maximize", study_name="XGBoost_Fraud_Detection")

    # Lambda-Funktion gibt Parameter and die Objective-Funktion weiter
    study.optimize(
        lambda trial: objective(trial, X_train, y_train, X_val, y_val),
        n_trials=n_trials
    )

    logger.info("Tuning abgeschlossen.")
    logger.info(f"Bester AUCPR auf Validationset: {study.best_value:.4f}")
    logger.info(f"Beste Hyperparameter: {study.best_params}")

    # Finales Training mit den besten Hyperparametern
    best_params = study.best_params
    best_params["objective"] = "binary:logistic"
    best_params["eval_metric"] = "aucpr"
    best_params["tree_method"] = "hist"
    best_params["device"] = "cuda"
    best_params["random_state"] = 42

    logger.info("Training des finalen Modells mit den besten Hyperparametern.")

    best_xgb_model = xgb.XGBClassifier(**best_params)
    best_xgb_model.fit(
        X_train,
        y_train,
        eval_set=[(X_val, y_val)],
        verbose=False
    )

    return best_xgb_model, best_params

In [ ]:
# Tuning durchführen (30 Runden als Start)
best_model, best_parameters = tune_and_train_xgboost(X_train, y_train, X_val, y_val, n_trials=30)

2026-03-30 17:40:07,638 - INFO - Starte Tuning mit 30 Trials...

[I 2026-03-30 17:40:07,639] A new study created in memory with name: XGBoost_Fraud_Detection
/usr/local/lib/python3.12/dist-packages/xgboost/core.py:751: UserWarning: [17:40:10] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)
[I 2026-03-30 17:40:10,288] Trial 0 finished with value: 0.7386421232067858 and parameters: {'max_depth': 10, 'learning_rate': 0.015343506465359261, 'n_estimators': 100, 'subsample': 0.8409236537874476, 'colsample_bytree': 0.799067559198293, 'scale_pos_weight': 634.2372381103538}. Best is trial 0 with value: 0.7386421232067858.
[I 2026-03-30 17:40:12,714] Trial 1 finished with value: 0.7878823149852384 and parameters: {'max_depth': 10, 'learning_rate': 0.02655600975024074, 'n_estimators': 352, 'subsample': 0.559679617005939, 'colsample_bytree': 0.7580740651136493, 'scale_pos_weight': 51.49509015224637}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:14,330] Trial 2 finished with value: 0.7778408643245747 and parameters: {'max_depth': 3, 'learning_rate': 0.019861575636970205, 'n_estimators': 319, 'subsample': 0.5315189755949769, 'colsample_bytree': 0.989773196134733, 'scale_pos_weight': 23.284185822938714}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:16,547] Trial 3 finished with value: 0.7525132974596959 and parameters: {'max_depth': 9, 'learning_rate': 0.011499345578485289, 'n_estimators': 282, 'subsample': 0.800092368286256, 'colsample_bytree': 0.8912941451290709, 'scale_pos_weight': 619.0983411050248}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:18,772] Trial 4 finished with value: 0.7685160334246598 and parameters: {'max_depth': 6, 'learning_rate': 0.01023293720586756, 'n_estimators': 404, 'subsample': 0.6793474133271012, 'colsample_bytree': 0.8635768715909213, 'scale_pos_weight': 576.8897786269306}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:20,401] Trial 5 finished with value: 0.771152344060166 and parameters: {'max_depth': 3, 'learning_rate': 0.011891778233786053, 'n_estimators': 312, 'subsample': 0.6979356647601561, 'colsample_bytree': 0.719399379674489, 'scale_pos_weight': 198.14846598169837}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:23,999] Trial 6 finished with value: 0.7788585724230644 and parameters: {'max_depth': 10, 'learning_rate': 0.02057088893822341, 'n_estimators': 387, 'subsample': 0.6268135865879183, 'colsample_bytree': 0.6903246990563859, 'scale_pos_weight': 691.8269633916001}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:25,507] Trial 7 finished with value: 0.7667259514028644 and parameters: {'max_depth': 5, 'learning_rate': 0.011343151142127776, 'n_estimators': 205, 'subsample': 0.5962850144783247, 'colsample_bytree': 0.7313131087961579, 'scale_pos_weight': 641.740340404297}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:27,496] Trial 8 finished with value: 0.7715430901095768 and parameters: {'max_depth': 7, 'learning_rate': 0.02740386845107854, 'n_estimators': 275, 'subsample': 0.9311158149983104, 'colsample_bytree': 0.7513057319617098, 'scale_pos_weight': 55.97603900988994}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:29,551] Trial 9 finished with value: 0.7725066929401532 and parameters: {'max_depth': 8, 'learning_rate': 0.011051170650044646, 'n_estimators': 294, 'subsample': 0.5367812547973573, 'colsample_bytree': 0.9379044576336768, 'scale_pos_weight': 56.92799278825341}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:32,347] Trial 10 finished with value: 0.7815472319573493 and parameters: {'max_depth': 8, 'learning_rate': 0.029961885690091162, 'n_estimators': 458, 'subsample': 0.9693877948059471, 'colsample_bytree': 0.6111576144559622, 'scale_pos_weight': 382.6736907480374}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:35,827] Trial 11 finished with value: 0.7822209167972041 and parameters: {'max_depth': 8, 'learning_rate': 0.029208849442452386, 'n_estimators': 480, 'subsample': 0.9121159165930142, 'colsample_bytree': 0.603556663162444, 'scale_pos_weight': 404.76227298044023}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:38,855] Trial 12 finished with value: 0.7809840984082718 and parameters: {'max_depth': 9, 'learning_rate': 0.025102186380014782, 'n_estimators': 483, 'subsample': 0.8810777870624654, 'colsample_bytree': 0.6063891755821846, 'scale_pos_weight': 374.7658273292546}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:41,364] Trial 13 finished with value: 0.7794470337857192 and parameters: {'max_depth': 8, 'learning_rate': 0.024070192983093888, 'n_estimators': 396, 'subsample': 0.7825387011094486, 'colsample_bytree': 0.6487362562082304, 'scale_pos_weight': 225.99274931287266}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:44,546] Trial 14 finished with value: 0.7844913239142852 and parameters: {'max_depth': 10, 'learning_rate': 0.022121634727184807, 'n_estimators': 495, 'subsample': 0.7029642189620476, 'colsample_bytree': 0.8185209259372485, 'scale_pos_weight': 491.03251720302364}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:46,892] Trial 15 finished with value: 0.7701015695620023 and parameters: {'max_depth': 10, 'learning_rate': 0.021415808861427573, 'n_estimators': 224, 'subsample': 0.7129322694390623, 'colsample_bytree': 0.8053482700859786, 'scale_pos_weight': 506.3016090009558}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:49,169] Trial 16 finished with value: 0.7743319172895001 and parameters: {'max_depth': 5, 'learning_rate': 0.01703770959661995, 'n_estimators': 356, 'subsample': 0.6297286279091039, 'colsample_bytree': 0.8066809283818712, 'scale_pos_weight': 215.16701132428096}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:51,850] Trial 17 finished with value: 0.7802105773073852 and parameters: {'max_depth': 9, 'learning_rate': 0.023415874479374058, 'n_estimators': 444, 'subsample': 0.5008790371744842, 'colsample_bytree': 0.8600598492028961, 'scale_pos_weight': 504.1094349173736}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:53,375] Trial 18 finished with value: 0.7600127221847394 and parameters: {'max_depth': 10, 'learning_rate': 0.017548182822548514, 'n_estimators': 121, 'subsample': 0.5709944889252326, 'colsample_bytree': 0.7840510801019708, 'scale_pos_weight': 288.92714966531594}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:55,896] Trial 19 finished with value: 0.7811061980856179 and parameters: {'max_depth': 7, 'learning_rate': 0.026126046375963143, 'n_estimators': 432, 'subsample': 0.7421064690407273, 'colsample_bytree': 0.8443389665802875, 'scale_pos_weight': 143.84032342819813}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:40:58,406] Trial 20 finished with value: 0.7718222320085472 and parameters: {'max_depth': 9, 'learning_rate': 0.014096384611543677, 'n_estimators': 352, 'subsample': 0.6265979172596166, 'colsample_bytree': 0.6830109512776477, 'scale_pos_weight': 460.49764075562956}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:41:02,293] Trial 21 finished with value: 0.7836355170032376 and parameters: {'max_depth': 8, 'learning_rate': 0.0299537478312653, 'n_estimators': 490, 'subsample': 0.9934415978135286, 'colsample_bytree': 0.7567972342183992, 'scale_pos_weight': 432.20225126816973}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:41:05,592] Trial 22 finished with value: 0.7776593388802564 and parameters: {'max_depth': 9, 'learning_rate': 0.02193577406259339, 'n_estimators': 499, 'subsample': 0.9995152791441986, 'colsample_bytree': 0.7635353646546611, 'scale_pos_weight': 332.72591454551565}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:41:08,562] Trial 23 finished with value: 0.7768942521950954 and parameters: {'max_depth': 10, 'learning_rate': 0.02729165386868253, 'n_estimators': 432, 'subsample': 0.8220015991984179, 'colsample_bytree': 0.8401179318412412, 'scale_pos_weight': 440.2681226379393}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:41:10,278] Trial 24 finished with value: 0.7757556424970417 and parameters: {'max_depth': 6, 'learning_rate': 0.01905524499294612, 'n_estimators': 236, 'subsample': 0.674304364045811, 'colsample_bytree': 0.7053843674249896, 'scale_pos_weight': 540.3533053040867}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:41:12,865] Trial 25 finished with value: 0.7644692488103875 and parameters: {'max_depth': 7, 'learning_rate': 0.022264990150356028, 'n_estimators': 173, 'subsample': 0.7626287356338003, 'colsample_bytree': 0.7585829116375642, 'scale_pos_weight': 440.0612789402837}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:41:15,903] Trial 26 finished with value: 0.7788109367347051 and parameters: {'max_depth': 9, 'learning_rate': 0.028094935724498324, 'n_estimators': 462, 'subsample': 0.873172006837354, 'colsample_bytree': 0.8919823198579862, 'scale_pos_weight': 288.12180250427906}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:41:18,421] Trial 27 finished with value: 0.7826127047882251 and parameters: {'max_depth': 10, 'learning_rate': 0.02552868139391093, 'n_estimators': 346, 'subsample': 0.7349141533374849, 'colsample_bytree': 0.654179343028924, 'scale_pos_weight': 302.34685814825013}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:41:20,969] Trial 28 finished with value: 0.7831276309168828 and parameters: {'max_depth': 8, 'learning_rate': 0.02343110239727357, 'n_estimators': 410, 'subsample': 0.6663976353973474, 'colsample_bytree': 0.819434839565307, 'scale_pos_weight': 145.75645355334896}. Best is trial 1 with value: 0.7878823149852384.
[I 2026-03-30 17:41:24,516] Trial 29 finished with value: 0.7693823186115846 and parameters: {'max_depth': 10, 'learning_rate': 0.014945146863261902, 'n_estimators': 497, 'subsample': 0.8531969925217987, 'colsample_bytree': 0.7805551473011273, 'scale_pos_weight': 563.0986870479733}. Best is trial 1 with value: 0.7878823149852384.

2026-03-30 17:41:24,517 - INFO - Tuning abgeschlossen.
2026-03-30 17:41:24,518 - INFO - Bester AUCPR auf Validationset: 0.7879
2026-03-30 17:41:24,519 - INFO - Beste Hyperparameter: {'max_depth': 10, 'learning_rate': 0.02655600975024074, 'n_estimators': 352, 'subsample': 0.559679617005939, 'colsample_bytree': 0.7580740651136493, 'scale_pos_weight': 51.49509015224637}
2026-03-30 17:41:24,519 - INFO - Training des finalen Modells mit den besten Hyperparametern.

**Deep Learning Ansatz**

---

Als Vergleich zum XGBoost wird einen Autoencoder gebaut. Die Idee ist, dass der Autoencoder ausschliesslich auf normale Transaktionen trainiert wird. Dadurch lernt er das Grundrauschen kennen. Bei einer Betrugsaktion sollte dann das Netz scheitern, diese zu rekonstruieren, was zu einem hohen Mean Squared Error (MSE) führt.

In [ ]:
import logging
import sys
import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np
from sklearn.metrics import average_precision_score
from typing import Tuple

In [ ]:
# Logging Setup
logging.basicConfig(
    level = logging.INFO,
    format = "%(asctime)s - %(levelname)s - %(message)s",
    force = True,
    stream = sys.stdout
)

logger = logging.getLogger(__name__)

In [ ]:
from numpy._core.defchararray import decode
# Neuronales Netz mit Autoencoder aufbauen
def build_and_train_autoencoder(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray
) -> Tuple[tf.keras.Model, float]:

  """
  Trainiert einen Autoencoder zur Anomalieerkennung von Fraud-Fällen.
  Trainiert ausschliesslich auf normalen Transaktionen.
  """

  # Daten filtern (nur normale Transaktionen)
  X_train_normal = X_train[y_train == 0]
  X_val_normal = X_val[y_val == 0]

  input_dim = X_train.shape[1]

  # Architektur des NN definieren (Encoder -> Bottleneck -> Decoder)
  input_layer = layers.Input(shape = (input_dim,))

  # Encoder (Komprimierung)
  encoded = layers.Dense(16, activation='relu')(input_layer)
  encoded = layers.Dropout(0.2)(encoded)                        # Overfitting verhindern
  encoded = layers.Dense(8, activation='relu')(encoded)        # Bottleneck

  # Decoder (Rekonstruktion)
  decoded = layers.Dense(16, activation='relu')(encoded)
  decoded = layers.Dense(input_dim, activation='linear')(decoded)

  # Modell zusammenbauen
  autoencoder = models.Model(inputs = input_layer, outputs = decoded)

  # Kompilieren
  autoencoder.compile(
      optimizer = tf.keras.optimizers.Adam(learning_rate = 0.001),
      loss = 'mse'
  )

  # Early Stopping
  early_stopping = tf.keras.callbacks.EarlyStopping(
      monitor = 'val_loss',
      patience = 5,
      restore_best_weights = True
  )


  # Training
  autoencoder.fit(
      X_train_normal,
      X_train_normal,
      epochs = 50,
      batch_size = 256,
      validation_data = (X_val_normal, X_val_normal),
      callbacks = [early_stopping],
      verbose = 0
  )
  logger.info("Training des Autoencoders abgeschlossen.")

  # Evaluierung
  logger.info("Berechnung des Rekonstrukionsfehlers auf Validierungsset.")
  reconstructions = autoencoder.predict(X_val, verbose = 0)

  mse = np.mean(np.power(X_val - reconstructions, 2), axis = 1)
  aucpr = average_precision_score(y_val, mse)

  logger.info(f"Autoencoder AUCPR auf Validationset: {aucpr:.4f}")

  return autoencoder, aucpr

In [ ]:
autoencoder_model, ae_aucpr = build_and_train_autoencoder(X_train, y_train, X_val, y_val)

2026-03-30 17:23:30,440 - INFO - Training des Autoencoders abgeschlossen.
2026-03-30 17:23:30,442 - INFO - Berechnung des Rekonstrukionsfehlers auf Validierungsset.
2026-03-30 17:23:34,949 - INFO - Autoencoder AUCPR auf Validationset: 0.0574

XGBoost schliesst im Vergleich zum Autoencoder deutlich besser ab. Aus diesem Grund wird das XGBoost-Modell in einem nächsten Schritt weiter optimiert.

Optimierung des XGBoost-Modells

In [ ]:
import numpy as np
from sklearn.metrics import precision_recall_curve, confusion_matrix, classification_report

In [ ]:
# Wahrscheinlichkeit auf dem Validierungsset vorhersagen
y_val_probs = best_model.predict_proba(X_val)[:, 1]

# Precision, Recall und Threshold berechnen
precision, recall, thresholds = precision_recall_curve(y_val, y_val_probs)

# Besten Threshold basierend auf dem F1-Score berechnen
f1_score = 2 * (precision * recall) / (precision + recall + 1e-12)
best_idx = np.argmax(f1_score)
optimal_threshold = thresholds[best_idx]

logger.info(f"Optimaler Threshold: {optimal_threshold:.4f}")
logger.info(f"Maximaler F1-Score auf Validation: {f1_score[best_idx]:.4f}")

2026-03-30 17:46:36,314 - INFO - Optimaler Threshold: 0.7349
2026-03-30 17:46:36,314 - INFO - Maximaler F1-Score auf Validation: 0.8235

In [ ]:
# Finale Evaluierung auf Testset
logger.info("Berechnung des AUCPR auf Testset.")

# Wahrscheinlichkeit für die Testdaten
y_test_probs = best_model.predict_proba(X_test)[:, 1]

# Vorhersage mit optimalem Threshold
y_test_pred = (y_test_probs >= optimal_threshold).astype(int)

# Ergebnis
print("\n" + "-" * 50)
print("Finales XGBoost-Modell auf Testset:")

print("\nConfusion Matrix:")
cm = confusion_matrix(y_test, y_test_pred)
print(f"Echte Normale Transaktionen (TN) korrekt erkannt: {cm[0][0]}")
print(f"Falscher Alarm (FP):                              {cm[0][1]}")
print(f"Betrug übersehen (FN):                            {cm[1][0]}")
print(f"Betrug erfolgreich erkannt (TP):                  {cm[1][1]}")

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred, target_names=["Normal", "Fraud"]))

2026-03-30 17:46:41,382 - INFO - Berechnung des AUCPR auf Testset.

--------------------------------------------------
Finales XGBoost-Modell auf Testset:

Confusion Matrix:
Echte Normale Transaktionen (TN) korrekt erkannt: 56880
Falscher Alarm (FP):                              7
Betrug übersehen (FN):                            20
Betrug erfolgreich erkannt (TP):                  55

Classification Report:
              precision    recall  f1-score   support

      Normal       1.00      1.00      1.00     56887
       Fraud       0.89      0.73      0.80        75

    accuracy                           1.00     56962
   macro avg       0.94      0.87      0.90     56962
weighted avg       1.00      1.00      1.00     56962